### ISSUE TITLE
Fix overlapping problem in force grid layout

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#13]
Strategy as suggested by Eetu is to just make the charge force nodes further away from each other than then distance between the grid points.

**Comment by esjewett** [comment]
This is pretty much working, but it looks to me like the additional collision force I added for the secondary nodes is not working. (Primary and secondary nodes should have different collision forces so that they pass through nodes of the other type.)

**Comment by jiemakel** [comment]
Looks extremely nice (except for the bug still affecting the secondary nodes)

**Comment by jiemakel** [comment]
The second layer bug reminds me, are we going to limit to two layers?

I'm thinking, should we generalize the layer handling to an arbitrary amount of layers with a layer array or equivalent? This would probably also streamline the way by which we implement the layer configuration (of dragging them on the top).

**Comment by esjewett** [comment]
@jiemakel I think the idea from @cncoleman's mock-ups is that we'll work to handle 3 layers. Arbitrary layers would be nice in some ways, but they pose problems for a lot of potential layouts. I think even 3 layers might be a stretch, but we'll see :-)

For some layouts, like a pure force-directed layout, we could definitely look at supporting arbitrary numbers of layers.

**Comment by esjewett** [comment]
There seems to be something going on here that is a limitation of the d3-force concept. I've asked on the mailing list along with an example of a different approach that seems to work a little better but still fails badly. If that is a no-go, we will probably have to define custom forces, which shouldn't be too bad but is something I would rather avoid.

**Comment by esjewett** [comment]
This wasn't working properly because I was trying to use behavior that d3-force didn't support. But it does now (or will as soon as there is a new release)! This should just start working at that time.

https://github.com/d3/d3-force/issues/72
