### ISSUE TITLE
Nodes never change back after being selected or moved

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#15]
When a node is selected it changes size and color, but never changes back after it is no longer selected.

- [x] Nodes turn green and large after being selected and don't change back
- [ ] Nodes turn dark when moved and don't turn back

**Comment by esjewett** [comment]
<img width="1197" alt="screen shot 2016-10-19 at 4 47 08 am" src="https://cloud.githubusercontent.com/assets/4822/19569226/97696600-96ba-11e6-84c0-fed690b58255.png">

**Comment by esjewett** [comment]
<img width="274" alt="screen shot 2016-10-20 at 11 45 21 am" src="https://cloud.githubusercontent.com/assets/4822/19569260/b9d58020-96ba-11e6-9600-44a566405b75.png">

**Comment by alexsherman** [comment]
I've fixed the problem with nodes staying green. 

As far as nodes staying black after being moved, I remember this as originally being intentional. Dark nodes used to signify that a node had been fixed to its spot after being dragged. What behavior do we actually want now?

**Comment by esjewett** [comment]
That's an interesting question about the black vs. grey node color after being moved. I think it does make sense to have some indication that a node has been manually positioned, but not sure if a small color difference like that is the right way to do it. Let's leave it for now.

**Comment by jiemakel** [comment]
Now that we default to nodes *not* moving after initial layout, I think there's no longer such a need to make that distinction in the UI.
