### ISSUE TITLE
Refactor autocompletion

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/fibra#16]
There's some design for this I've done at https://docs.google.com/drawings/d/18pUS2zRrOkgOEpZiGhRGyQIPGBHacaYsEJnngPxHsRQ/edit (center column), but that doesn't contain everything I've though about. I'll first have to update that design, and then implement it. 

Technically, I'm also going to make it work faster.

**Comment by cncoleman** [comment]
What is the status on this?
