### ISSUE TITLE
Detail design of adding new nodes in CONSTRUCT

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/fibra#19]
Similarly to adding links, what exactly are the steps for adding new nodes in CONSTRUCT?

My initial thoughts are that when you are in "drawing mode", you constantly see a phantom node at the nearest grid point. Right clicking or similar will then add a new node there, with its type defined by the layer it is on. It will then immediately also ask for the new node's label. 

But just the label, or should it also provide a form for other properties? 

Another alternative is that you can just add nodes anywhere (particularly if we're not on a fixed grid - are we BTW forcing the fixed grid, or will we continue to support a non-fixed one?). Then, the type would be selected similarly to the link type (or maybe there in addition could be a dropdown somewhere that shows the current add type and allows you to change it also from there?), and after that we move to adding labels and properties as before.

**Comment by cncoleman** [comment]
If we take the 'phantom node' approach. There is really no reason to right-click. If there is no node at a grid point, there is no reason to click unless you are adding a node. 

Agreed that the type is defined by the layer. switching between layers is something we will want to enable easily. But let's just start by adding nodes on the grid with a requirement to either select the appropriate layer "tab" or to modify the type in editing node properties. 

Let's start with the scalable fixed grid. We test that first and then determine what is needed.
