### ISSUE TITLE
How do I get to my projects?

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/fibra#195]

**Comment by esjewett** [comment]
Go to http://hdlab.stanford.edu/fibra/test/#!/projects

They should show up under the heading "Personal projects on the public LDF.fi endpoint". If you don't see this heading, you need to log in (link in the upper right corner).

Is this not showing up for you? Or are projects missing?

**Comment by esjewett** [comment]
Sorry, I answered this question literally and I take it that it is meant to be a design question?

**Comment by cncoleman** [comment]
Yes. It was a design question. Its the kind of question a user should not need to ask.

---

Nicole Coleman
Digital Research Architect
Stanford University Libraries
+1.650.575.9958
________________________________
