### ISSUE TITLE
Recon json file for people VIAF and people Wikidata

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/fibra#207]
This is high priority so that we can usefully test RECON with Dan's use case and his data. He uses VIAF and Wikidata for reconciliation of people.

**Comment by esjewett** [comment]
Specifically, we would need this file to match against the ldf.fi VIAF endpoint and return a full VIAF ID in the Match field. Sound reasonable @jiemakel?

**Comment by jiemakel** [comment]
eminently.

**Comment by jiemakel** [comment]
VIAF person and general Wikidata configurations added in jiemakel/recon@d281af31a0d56db30cf319bf44a7f47626a991ec
