### ISSUE TITLE
Create a dummy "SELECT" component with pre-configured selections.

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/fibra#21]

**Comment by jiemakel** [comment]
Added an initial space for this, but still need the actual selections to choose from.

**Comment by cncoleman** [comment]
Hope to have Selections by tomorrow defined by Dan and our visitors. With Dan, I'm going to work on defining a select FOR Procope. How difficult would it be to remove Procope from the Pre-Configuration so that we can instead use it as our sample project. We arrive at Procope by pulling data from the pre-configured sources, based on a Selection (local data set) that Dan defines.

**Comment by jiemakel** [comment]
Easy. Also, there are actually multiple data sets inside my current Procope container, which could be teased out. They are:
/ee/
/dalembert/
/placeauthority/
/main/ 
/grandtour/ (It also seems I've stuffed the grand tour data in there as well)
/place-enrich/ (place coordinates, probably auto-sourced for places outside of the place authority?)

So, I guess the way forward would be to move all of these out to their own "archives", and then (the end product of) Procope would just be the main one, plus possibly the place authority?
