### ISSUE TITLE
Sort typescript code and templates in subfolders by functionality

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/fibra#24]
But, should we then store a component's template in the same directory as the component?

**Comment by esjewett** [comment]
I would say yes. We can put the CSS into the component folders too. CSS in those folders should be scoped to the component so we don't have to search all over for a global selector hiding in a component CSS file (though it's not so hard to find them with browser dev tools these days), so all the CSS selectors in the file would need to start with the component name. e.g.

```css
[my-component-name] h1 .my-style {

}
```

**Comment by jiemakel** [comment]
Implemented in 0b9cd79b7e75d98ec16c753fc18e7dc3569df376.
