### ISSUE TITLE
Type label in selectedTypes object

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#27]
Currently the structure of the types in selectedTypes looks like:

`{value: "http://www.cidoc-crm.org/cidoc-crm/E74_Group", termType: "NamedNode", __className: "NamedNode"}`

I think in the type properties of the actual items there is a readable label derived in some way. Would it be possible to have this label information on this object as well?

**Comment by jiemakel** [comment]
Hmm. Yes, but I'm not sure I consider the `selectedTypes` field stable, or a good source to use in construct for the types, as in the future, individual types from external sources will sometimes need to be mapped to other local types in the configuration.

This does specify a need for a place for this "local data model" somewhere in the configuration service,  but until I make that (or actually populate the `globalDataModelConfiguration` that is already there as a placeholder), I suggest you continue using the tree query.

**Comment by esjewett** [comment]
Ok, I guess I'll just take the output of the tree query and transform it to a flat output that is just the leaves. That is probably a better approach anyway. Thanks!
