### ISSUE TITLE
API for adding/modifying properties of an Item

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#29]
May already exist, but Alex and I aren't clear on how to go about this.

**Comment by jiemakel** [comment]
You can add/remove properties directly using SparqlUpdateService, but then you have to know the graph the triples are going into, which isn't actually currently being exposed from the configuration.

There should probably be a method in `Item` that does this, modifying both the local as well as the remote data? And we'd want to implement this relying on #6 ?

(later, this also needs to support and handle directional/bidirectional relationships transparently)

**Comment by esjewett** [comment]
Yup, I think that sounds right. I'll see what I can do regarding #6...

**Comment by jiemakel** [comment]
Heh, while looking at `SparqlItemService`, I found out that I've actually at one point implemented `alterItem` already. 

It should work, but unfortunately, does not yet respect working sets, and will thus currently put the data in the wrong graph.

**Comment by jiemakel** [comment]
This should now work properly.
