### ISSUE TITLE
Authentication required? 

### ISSUE THREAD

**Issue by alexsherman** [humanitiesplusdesign/fibra#3]
I am being asked for a username and password when trying to add or delete items. Is there a specific username and password needed for this?

![fibra issue2](https://cloud.githubusercontent.com/assets/5248189/16965307/6b66803c-4db4-11e6-8dc1-9fd198c444d7.png)

**Comment by esjewett** [comment]
Shared the test username and password privately. Eventually we need to determine a way to handle this for the final application, but for now we will just use the test database while working out the user interaction.

**Comment by cncoleman** [comment]
Can you re-send?

**Comment by esjewett** [comment]
Sent - sorry for the delay.
