### ISSUE TITLE
Switch Explore/Construct over to a "blank slate" approach

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#45]
At the moment, will probably go with client-side management of the currently displayed items. @jiemakel is thinking further about this.

**Comment by esjewett** [comment]
Related to #41

**Comment by jiemakel** [comment]
Having given it further thought, I think we want to keep the following state on the client:
 * ids of nodes visible in construct (the "construct set")
 * position of nodes in construct

Data on the nodes should still be brought in from the server on initializing the construct view. I'll add a `getItems` to `SparqlItemService` that will bring in information on multiple items using a single query.

**Comment by esjewett** [comment]
I think this makes sense and will go forward based on this. Until `getItems` is available, I will just use multiple calls to `getItem`. I think we probably still need to decide on the semantics of create/delete, but we will have a situation in which those functions are encapsulated in actions and can easily be extended to update client-side or server-side state, depending on what we decide.
