### ISSUE TITLE
Add `getItems` method to `SparqlItemService`

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#46]

**Comment by esjewett** [comment]
Hi @jiemakel - would it be possible to do this relatively soon? Right now I think the biggest source of lag in display is the multiple calls to to `getItem`, so I suspect that consolidating them all would speed things up quite a bit. Thanks!

**Comment by jiemakel** [comment]
I already implemented half of this, but then moved on to something else. I'll certainly do all the efficiency refactorings next when I get the chance.

**Comment by jiemakel** [comment]
Now functional, and hooked up to construct. 

Also, the API now makes use of promise.notify to allow the UI to update itself iteratively as responses stream in through the different endpoints. Construct doesn't make use of this right now, as I also added a flag to it to only query the primary endpoint, but I did test this, and it adds nicely to the interactivity of the UI when making remote calls. 

I'll implement this next into the autocompletion, where it should affect performance much more.
