### ISSUE TITLE
autocomplete component can return very large amounts of data

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#47]
I searched for "Charles" in the all datasources configuration and this is a screenshot of the request after a minute or so (it got up to almost a gigabyte before Safari crashed):

<img width="1177" alt="screen shot 2016-12-05 at 1 37 11 pm" src="https://cloud.githubusercontent.com/assets/4822/20899463/22842dc0-baf0-11e6-9473-178cfbebfcfc.png">

**Comment by jiemakel** [comment]
Heh. Currently, the autocompletion is returning only a limited number of prefix matches, but **all** complete matches. I guess we need to apply the limit on all matches, but then allow the user to raise that limit through the UI (a clickable `...` or something)

**Comment by esjewett** [comment]
Got it. Yeah, it seems to work better for slightly less common names. I'm using "David Hume" as my example now...
