### ISSUE TITLE
Need tray or modal for displaying selected item detail

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#5]
Initially should just display the sparql-item-component

**Comment by jiemakel** [comment]
Now shown as a tooltip, but we really need to figure out where to put this, and the interaction in general (i.e. is this just for showing [a little] more info, or for also editing?)

**Comment by jiemakel** [comment]
Just looked at [the current design](https://github.com/humanitiesplusdesign/fibra/blob/gh-pages/assets/designs/Fibra-Construct.pdf), which specifies a badge/popover. That will work when we have a very limited amount of properties, but won't if we have as many of them as are now coming over from the external sources.

**Comment by esjewett** [comment]
If we just show the local properties, I think it might be OK. But we need to think about another interface for letting users choose the remote properties they want to pull in.

Right now, this is showing all properties (local and remote), correct?

Thanks!

**Comment by jiemakel** [comment]
Yes, local and remote. I'm halfway through restructuring the item view to look like the right hand side of: ![the editing focused view](https://docs.google.com/drawings/d/18pUS2zRrOkgOEpZiGhRGyQIPGBHacaYsEJnngPxHsRQ/pub?w=1440&h=1080) After that the properties will be structurally segregated, and it'll be easy to add a toggle to draw in just the local ones.

But yeah, we definitely need to come up with the "local import" interface quickly.

**Comment by cncoleman** [comment]
I'll be able to work up local import interface next week.

**Comment by jiemakel** [comment]
The above property layout has now been implemented, and I deployed it also to http://hdlab.stanford.edu/fibra/test/
