### ISSUE TITLE
Show/Hide Links. Hide by Default. 

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/fibra#61]
When I expand a node to see, for example, everyone the person "possibly met" I already know they are 'linked' somehow, so I don't need to see those links by default. I can turn them on when I want to see connections within that group or when I want to see how they are connected via another node type.
See attached mockup based on Excellence Networks for placing that option as well as the layout option.

![settings_bar_construct 001](https://cloud.githubusercontent.com/assets/288005/21051191/e8029506-bdd3-11e6-8f3e-03525a32968d.png)

[See it in action at the site.](http://excellence-networks.net/#pharmacology-toxicology-and-pharmaceutics/network/_/probability/true)

**Comment by esjewett** [comment]
Need to freshen up the UI here. Will open a new issue for that.
