### ISSUE TITLE
Add statistics to CONFIGURE

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/fibra#67]

**Comment by jiemakel** [comment]
Implemented (although needs a bit filtering as currently People is being shown twice), but need an opinion from @cncoleman on hierarchy. 

Currently, statistics are shown per authority/archive, but I was thinking that maybe we should group them first by type before authority, so we'd have:

Authorities:
 * People
    * VIAF (21 million)
    * ULAN (200k)
 * Group
    * VIAF (5 million)
    * ULAN (40k)
 * Places
   * TGN (1,7 million)
   * Geonames (10 million)

Instead of the current
Authorities:
 * VIAF
   * Person (21 million)
   * Group (5 million)
 * ULAN
   * Person (200k)
   * Group (40k)
 * TGN
    * Place (1,7 million)
 * Geonames
    * Place (10 million)

and so on. On the other hand, while I think this would work well for authorities, it will probably not work as well for archives, where the contents of the archive are more interrelated and their interrelations are important, so e.g.
Archives:
 * FBTEE
   * Book (n)
   * Person (n)
   * Place (n) 

is more sensible than having them separately?

**Comment by cncoleman** [comment]
I'm closing this issue since we are using a somewhat different architecture since the July design meeting.
