### ISSUE TITLE
Another data source to add

### ISSUE THREAD

**Issue by cncoleman** [humanitiesplusdesign/fibra#7]
Our partners in the French Book Trade project have made their data freely available here:

http://fbtee.uws.edu.au/main/download-database/

This publication data could be an excellent addition with significant overlaps with our current test data sets.  The project lead, Simon Burrows, will be visiting Stanford at the end of October. It's always more effective to demo a tool when it includes material that is off interest to the user!

**Comment by jiemakel** [comment]
First version of the data conversion now online at http://ldf.fi/fbtee/. Not inked to Fibra yet, though. 

Was a refreshingly complex and well-thought out dataset, BTW.

**Comment by jiemakel** [comment]
Now also in Fibra (along with VIAF, ULAN, TGN, LCNames).
