### ISSUE TITLE
Labeling of nodes appears to be broken

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#84]

**Comment by esjewett** [comment]
Working for me, so I'm not sure what the problem was that I was seeing.

**Comment by cncoleman** [comment]
Maybe it's just latency. Actions do seem very slow to execute.


________________________________

**Comment by esjewett** [comment]
@cncoleman Yeah, I thought so too. Or another issue that broke the whole application or the web worker. I will wait until it happens to me again an investigate more thoroughly.
