### ISSUE TITLE
Create pre-configured configurations AND actual data/working sets

### ISSUE THREAD

**Issue by jiemakel** [humanitiesplusdesign/fibra#9]
For robust testing, we want to have multiple test scenarios with both 1) different datasets configured (Early Modern / Ancient config) and 2) different data in the current working / visualization set (to simulate individual researchers' individual sessions/tasks/questions). 

I'll add the support needed for storing and switching between these into the code and supporting infrastructure, though the ability to create these in an UI will come at a significantly later stage.

**Comment by cncoleman** [comment]
This is adding to #1"CONFIGURE" the #2 "SELECT" component. Agreed that we cannot achieve our first step of "Find, Autocomplete, Expand" until we have pre-selections in place. With the early modern configuration, we have too much to work with.

**Comment by jiemakel** [comment]
Just committed progress related to this. What is missing is that CONSTRUCT is still making use of a temporary query that does not take the configuration into account. The reason CONSTRUCT is doing this is that as of yet, none of the data items actually have any local content apart from links to the outside sources. 

Next steps will thus be to:
 - [ ] add some local data to each of the preconfigured sets
 - [ ] update the queries used in CONSTRUCT

**Comment by esjewett** [comment]
Question for @jiemakel on the data set with Locke's 2-degrees plus related places. It doesn't look like the people in the dataset have properties for birth/death place, so they won't link to the places and the places won't show up in the sunbursts for the people. I suspect that this is due to the getItems API not returning merged entities, so we just don't have the EMLO birth/death place info in the explore view. Is this right?

**Comment by jiemakel** [comment]
EMLO actually didn't have birth/death places, only dates. So I decided to take all places where they sent letters from, and linked these to them using the `related` property. There weren't too many of these so you have to experiment to find them.

**Comment by esjewett** [comment]
Ah, I see them. Thanks!

Which database has the birth/death information? VIAF?

**Comment by jiemakel** [comment]
I'm not sure. I'll check.
