### ISSUE TITLE
Export as RDF

### ISSUE THREAD

**Issue by esjewett** [humanitiesplusdesign/fibra#94]

**Comment by jiemakel** [comment]
http://ldf.fi/fibra/sparql?graph=http://ldf.fi/fibra/set1/
http://ldf.fi/fibra/sparql?graph=http://ldf.fi/fibra/set2/
http://ldf.fi/fibra/sparql?graph=http://ldf.fi/fibra/set3/

http://ldf.fi/fibra/sparql?graph=http://ldf.fi/fibra/set1/&force-accept=text/plain
http://ldf.fi/fibra/sparql?graph=http://ldf.fi/fibra/set1/&force-accept=application/rdf+xml
http://ldf.fi/fibra/sparql?graph=http://ldf.fi/fibra/set1/&force-accept=application/ld+json

**Comment by alexsherman** [comment]
Just to be sure I understand--the RDF format is completely contained in the links Eetu posted above and I just need to implement an interface to export these?

**Comment by jiemakel** [comment]
Yes. So in essence, you just need a button that redirects to the appropriate link (which you need to customize for the graph. You need to dig that from the configuration)

**Comment by esjewett** [comment]
It's a little more complicated if you want to control the filename or make it download as a file in different browsers, but that'll be a start.

**Comment by jiemakel** [comment]
The extension for the Turtle format should be `.ttl`. I was able to load this export at least in Gephi with the [SemanticWebImport](https://marketplace.gephi.org/plugin/semanticwebimport/)-plugin.
